spring.profiles.active=dev
spring.application.name=promed
server.port=8080
spring.jackson.time-zone=America/Sao_Paulo
logging.level.org.springframework=INFO
logging.level.br.com.andreleonam.promed=DEBUG
spring.datasource.sql-script-encoding=UTF-8