@startuml

enum StatusExame {
  SOLICITADO
  RECEBIDO
}

enum Turno {
  MANHA
  TARDE
  NOITE
}

enum Encaminhamento {
  ESPECIALISTA
  INTERNACAO
  SERVICO_EMERGENCIA
}

enum TipoConsulta {
  PRIMEIRA_VEZ
  RETORNO
}

enum EstadoCivil {
  CASADO
  DIVORCIADO
  UNIAO_ESTAVEL
  VIUVO
  SOLTEIRO
}

enum StatusCadastro {
  INCOMPLETO
  COMPLETO
}

enum StatusConsulta {
  AGENDADA
  CONFIRMADA
  REALIZADA
  CANCELADA
}

enum TipoPrioridade {
  NENHUMA
  IDOSO
  GESTANTE
  DEFICIENCIA
}

enum StatusPendencia {
  PENDENTE
  APROVADO
  REJEITADO
}

enum TipoTelefone {
  FIXO
  CELULAR
  COMERCIAL
}

enum Escolaridade {
  FUNDAMENTAL_INCOMPLETO
  FUNDAMENTAL_COMPLETO
  MEDIO_INCOMPLETO
  MEDIO_COMPLETO
  SUPERIOR_INCOMPLETO
  SUPERIOR_COMPLETO
  POS_GRADUACAO
  MESTRADO
  DOUTORADO
}

enum TipoDocumento {
  CERTIDAO_NASCIMENTO
  PASSAPORTE
  OUTROS
}


enum Sexo {
  MASCULINO,
  FEMININO,
  OUTRO
}

@enduml